title: Konda Mtawali
theme: minima
author: Konda Mtawali
email: kmtawali@tutanota.com
description: Insert description here.

twitter_username: atlanteangold
github_username: kkmtawali

show_excerpts: true
