title: Konda Mtawali
theme: minima
author: Konda Mtawali
email: kmtawali@tutanota.com
description: A personal digital resume, autobiography, and project hub.

twitter_username: atlanteangold
github_username: kkmtawali

show_excerpts: true
