title: Kkmtawali's homepage
theme: minima
author: Konda K. Mtawali
email: kmtawali@tutanota.com
description: Insert description here.

twitter_username: atlanteangold
github_username: kkmtawali

show_excerpts: true
